print("1. ***")
print("   ***")
print("   ***")
print("2.  * ")
print("   ***")
print("    * ")
print("3. 999")
print("   888")
print("   777")
print("4. 111")
print("   222")
print("   333")
a = int(input("Введите цифру от 1 до 4: "))

if a == 1:
    print("1. ***")
    print("   ***")
    print("   ***")
if a == 2:
    print("2.  * ")
    print("   ***")
    print("    * ")
if a == 3:
    print("3. 999")
    print("   888")
    print("   777")
if a == 4:
    print("4. 111")
    print("   222")
    print("   333")